-- GENERAL
require('settings')
require('plugins')
require('keymap')
require('colors')
require('auto')
require('utils')
require('functions')

-- LSP
require('lsp')
require('lsp.bash')
require('lsp.json')
require('lsp.latex')
require('lsp.lua')
require('lsp.vim')
require('lsp.efm')

-- PLUGIN CONFIGS
require('plugins.autopairs')
require('plugins.barbar')
require('plugins.colorizer')
require('plugins.comment')
require('plugins.cmp')
require('plugins.dashboard')
require('plugins.galaxyline')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.lspsaga')
require('plugins.markdown-preview')
require('plugins.nvim-dap')
require('plugins.nvim-tree')
require('plugins.sniprun')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.treesitter')
require('plugins.ultisnips')
require('plugins.whichkey')

